spring:
    application:
        name: aPizza
    jackson:
        property-naming-strategy: SNAKE_CASE
    flyway:
        locations: classpath:/db/migration
        schemas: person
        baselineOnMigrate: true
        enabled: true
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=person
        username: postgres
        password: admin